apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground
spec:
  containers:
           - name: c1  
             image: nginx:1.17.6-alpine
             env:
             - name: MY_NODE_NAME
               valueFrom:
                 fieldRef:
                   fieldPath: spec.nodeName
           - name: c2
             image: busybox
             command: ["/bin/sh", "-c"]
             args:
               - while true; do
                  date >> /date/date.log;
                  sleep 1;
                 done
             volumeMounts:
                     - mountPath: /date
                       name: date
           - name: c3
             image: busybox
             command: ["tail", "-f", "/date/date.log"]
             volumeMounts:
                     - mountPath: /date
                       name: date
  volumes: 
    - name: date
      emptyDir: {}

