apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
    company: globant
  name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

